name: nfl-oline
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - ipython
  - jupyter
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - tqdm
  - ffmpeg
  - shapely
  - pip:
    - nfl_data_py